'use strict';

const floorData = [
  { buildingId: 1, roomNumber: 'A/101', floorNumber: 1 },
  { buildingId: 1, roomNumber: 'A/102', floorNumber: 1 },
  { buildingId: 1, roomNumber: 'A/103', floorNumber: 1 },
  { buildingId: 1, roomNumber: 'A/104', floorNumber: 1 },
  { buildingId: 1, roomNumber: 'A/105', floorNumber: 1 },
  { buildingId: 1, roomNumber: 'A/106', floorNumber: 1 },
  { buildingId: 1, roomNumber: 'A/107', floorNumber: 1 },
  { buildingId: 1, roomNumber: 'A/108', floorNumber: 1 },

  { buildingId: 1, roomNumber: 'A/201', floorNumber: 2 },
  { buildingId: 1, roomNumber: 'A/202', floorNumber: 2 },
  { buildingId: 1, roomNumber: 'A/203', floorNumber: 2 },
  { buildingId: 1, roomNumber: 'A/204', floorNumber: 2 },
  { buildingId: 1, roomNumber: 'A/205', floorNumber: 2 },
  { buildingId: 1, roomNumber: 'A/206', floorNumber: 2 },
  { buildingId: 1, roomNumber: 'A/207', floorNumber: 2 },
  { buildingId: 1, roomNumber: 'A/208', floorNumber: 2 },

  { buildingId: 1, roomNumber: 'A/301', floorNumber: 3 },
  { buildingId: 1, roomNumber: 'A/302', floorNumber: 3 },
  { buildingId: 1, roomNumber: 'A/303', floorNumber: 3 },
  { buildingId: 1, roomNumber: 'A/304', floorNumber: 3 },
  { buildingId: 1, roomNumber: 'A/305', floorNumber: 3 },
  { buildingId: 1, roomNumber: 'A/306', floorNumber: 3 },
  { buildingId: 1, roomNumber: 'A/307', floorNumber: 3 },
  { buildingId: 1, roomNumber: 'A/308', floorNumber: 3 },

  { buildingId: 1, roomNumber: 'A/401', floorNumber: 4 },
  { buildingId: 1, roomNumber: 'A/402', floorNumber: 4 },
  { buildingId: 1, roomNumber: 'A/403', floorNumber: 4 },
  { buildingId: 1, roomNumber: 'A/404', floorNumber: 4 },
  { buildingId: 1, roomNumber: 'A/405', floorNumber: 4 },
  { buildingId: 1, roomNumber: 'A/406', floorNumber: 4 },
  { buildingId: 1, roomNumber: 'A/407', floorNumber: 4 },
  { buildingId: 1, roomNumber: 'A/408', floorNumber: 4 },

  { buildingId: 1, roomNumber: 'A/501', floorNumber: 5 },
  { buildingId: 1, roomNumber: 'A/502', floorNumber: 5 },
  { buildingId: 1, roomNumber: 'A/503', floorNumber: 5 },
  { buildingId: 1, roomNumber: 'A/504', floorNumber: 5 },
  { buildingId: 1, roomNumber: 'A/505', floorNumber: 5 },
  { buildingId: 1, roomNumber: 'A/506', floorNumber: 5 },
  { buildingId: 1, roomNumber: 'A/507', floorNumber: 5 },
  { buildingId: 1, roomNumber: 'A/508', floorNumber: 5 },

  { buildingId: 1, roomNumber: 'A/601', floorNumber: 6 },
  { buildingId: 1, roomNumber: 'A/602', floorNumber: 6 },
  { buildingId: 1, roomNumber: 'A/603', floorNumber: 6 },
  { buildingId: 1, roomNumber: 'A/604', floorNumber: 6 },
  { buildingId: 1, roomNumber: 'A/605', floorNumber: 6 },
  { buildingId: 1, roomNumber: 'A/606', floorNumber: 6 },
  { buildingId: 1, roomNumber: 'A/607', floorNumber: 6 },
  { buildingId: 1, roomNumber: 'A/608', floorNumber: 6 },

  { buildingId: 1, roomNumber: 'A/701', floorNumber: 7 },
  { buildingId: 1, roomNumber: 'A/702', floorNumber: 7 },
  { buildingId: 1, roomNumber: 'A/703', floorNumber: 7 },
  { buildingId: 1, roomNumber: 'A/704', floorNumber: 7 },
  { buildingId: 1, roomNumber: 'A/705', floorNumber: 7 },
  { buildingId: 1, roomNumber: 'A/706', floorNumber: 7 },
  { buildingId: 1, roomNumber: 'A/707', floorNumber: 7 },
  { buildingId: 1, roomNumber: 'A/708', floorNumber: 7 },

  { buildingId: 1, roomNumber: 'A/801', floorNumber: 8 },
  { buildingId: 1, roomNumber: 'A/802', floorNumber: 8 },
  { buildingId: 1, roomNumber: 'A/803', floorNumber: 8 },
  { buildingId: 1, roomNumber: 'A/804', floorNumber: 8 },
  { buildingId: 1, roomNumber: 'A/805', floorNumber: 8 },
  { buildingId: 1, roomNumber: 'A/806', floorNumber: 8 },
  { buildingId: 1, roomNumber: 'A/807', floorNumber: 8 },
  { buildingId: 1, roomNumber: 'A/808', floorNumber: 8 },

  { buildingId: 1, roomNumber: 'A/901', floorNumber: 9 },
  { buildingId: 1, roomNumber: 'A/902', floorNumber: 9 },
  { buildingId: 1, roomNumber: 'A/903', floorNumber: 9 },
  { buildingId: 1, roomNumber: 'A/904', floorNumber: 9 },
  { buildingId: 1, roomNumber: 'A/905', floorNumber: 9 },
  { buildingId: 1, roomNumber: 'A/906', floorNumber: 9 },
  { buildingId: 1, roomNumber: 'A/907', floorNumber: 9 },
  { buildingId: 1, roomNumber: 'A/908', floorNumber: 9 },

  { buildingId: 1, roomNumber: 'A/1001', floorNumber: 10 },
  { buildingId: 1, roomNumber: 'A/1002', floorNumber: 10 },
  { buildingId: 1, roomNumber: 'A/1003', floorNumber: 10 },
  { buildingId: 1, roomNumber: 'A/1004', floorNumber: 10 },
  { buildingId: 1, roomNumber: 'A/1005', floorNumber: 10 },
  { buildingId: 1, roomNumber: 'A/1006', floorNumber: 10 },
  { buildingId: 1, roomNumber: 'A/1007', floorNumber: 10 },
  { buildingId: 1, roomNumber: 'A/1008', floorNumber: 10 },

  { buildingId: 1, roomNumber: 'A/1101', floorNumber: 11 },
  { buildingId: 1, roomNumber: 'A/1102', floorNumber: 11 },
  { buildingId: 1, roomNumber: 'A/1103', floorNumber: 11 },
  { buildingId: 1, roomNumber: 'A/1104', floorNumber: 11 },
  { buildingId: 1, roomNumber: 'A/1105', floorNumber: 11 },
  { buildingId: 1, roomNumber: 'A/1106', floorNumber: 11 },
  { buildingId: 1, roomNumber: 'A/1107', floorNumber: 11 },
  { buildingId: 1, roomNumber: 'A/1108', floorNumber: 11 },

  { buildingId: 1, roomNumber: 'A/1201', floorNumber: 12 },
  { buildingId: 1, roomNumber: 'A/1202', floorNumber: 12 },
  { buildingId: 1, roomNumber: 'A/1203', floorNumber: 12 },
  { buildingId: 1, roomNumber: 'A/1204', floorNumber: 12 },
  { buildingId: 1, roomNumber: 'A/1205', floorNumber: 12 },
  { buildingId: 1, roomNumber: 'A/1206', floorNumber: 12 },
  { buildingId: 1, roomNumber: 'A/1207', floorNumber: 12 },
  { buildingId: 1, roomNumber: 'A/1208', floorNumber: 12 },

  { buildingId: 1, roomNumber: 'A/1301', floorNumber: 13 },
  { buildingId: 1, roomNumber: 'A/1302', floorNumber: 13 },
  { buildingId: 1, roomNumber: 'A/1303', floorNumber: 13 },
  { buildingId: 1, roomNumber: 'A/1304', floorNumber: 13 },
  { buildingId: 1, roomNumber: 'A/1305', floorNumber: 13 },
  { buildingId: 1, roomNumber: 'A/1306', floorNumber: 13 },
  { buildingId: 1, roomNumber: 'A/1307', floorNumber: 13 },
  { buildingId: 1, roomNumber: 'A/1308', floorNumber: 13 },

  { buildingId: 1, roomNumber: 'A/1401', floorNumber: 14 },
  { buildingId: 1, roomNumber: 'A/1402', floorNumber: 14 },
  { buildingId: 1, roomNumber: 'A/1403', floorNumber: 14 },
  { buildingId: 1, roomNumber: 'A/1404', floorNumber: 14 },
  { buildingId: 1, roomNumber: 'A/1405', floorNumber: 14 },
  { buildingId: 1, roomNumber: 'A/1406', floorNumber: 14 },
  { buildingId: 1, roomNumber: 'A/1407', floorNumber: 14 },
  { buildingId: 1, roomNumber: 'A/1408', floorNumber: 14 },

  { buildingId: 1, roomNumber: 'A/1501', floorNumber: 15 },
  { buildingId: 1, roomNumber: 'A/1502', floorNumber: 15 },
  { buildingId: 1, roomNumber: 'A/1503', floorNumber: 15 },
  { buildingId: 1, roomNumber: 'A/1504', floorNumber: 15 },
  { buildingId: 1, roomNumber: 'A/1505', floorNumber: 15 },
  { buildingId: 1, roomNumber: 'A/1506', floorNumber: 15 },
  { buildingId: 1, roomNumber: 'A/1507', floorNumber: 15 },
  { buildingId: 1, roomNumber: 'A/1508', floorNumber: 15 },

  { buildingId: 2, roomNumber: 'B/101', floorNumber: 1 },
  { buildingId: 2, roomNumber: 'B/102', floorNumber: 1 },
  { buildingId: 2, roomNumber: 'B/103', floorNumber: 1 },
  { buildingId: 2, roomNumber: 'B/104', floorNumber: 1 },
  { buildingId: 2, roomNumber: 'B/105', floorNumber: 1 },
  { buildingId: 2, roomNumber: 'B/106', floorNumber: 1 },
  { buildingId: 2, roomNumber: 'B/107', floorNumber: 1 },
  { buildingId: 2, roomNumber: 'B/108', floorNumber: 1 },

  { buildingId: 2, roomNumber: 'B/201', floorNumber: 2 },
  { buildingId: 2, roomNumber: 'B/202', floorNumber: 2 },
  { buildingId: 2, roomNumber: 'B/203', floorNumber: 2 },
  { buildingId: 2, roomNumber: 'B/204', floorNumber: 2 },
  { buildingId: 2, roomNumber: 'B/205', floorNumber: 2 },
  { buildingId: 2, roomNumber: 'B/206', floorNumber: 2 },
  { buildingId: 2, roomNumber: 'B/207', floorNumber: 2 },
  { buildingId: 2, roomNumber: 'B/208', floorNumber: 2 },

  { buildingId: 2, roomNumber: 'B/301', floorNumber: 3 },
  { buildingId: 2, roomNumber: 'B/302', floorNumber: 3 },
  { buildingId: 2, roomNumber: 'B/303', floorNumber: 3 },
  { buildingId: 2, roomNumber: 'B/304', floorNumber: 3 },
  { buildingId: 2, roomNumber: 'B/305', floorNumber: 3 },
  { buildingId: 2, roomNumber: 'B/306', floorNumber: 3 },
  { buildingId: 2, roomNumber: 'B/307', floorNumber: 3 },
  { buildingId: 2, roomNumber: 'B/308', floorNumber: 3 },

  { buildingId: 2, roomNumber: 'B/401', floorNumber: 4 },
  { buildingId: 2, roomNumber: 'B/402', floorNumber: 4 },
  { buildingId: 2, roomNumber: 'B/403', floorNumber: 4 },
  { buildingId: 2, roomNumber: 'B/404', floorNumber: 4 },
  { buildingId: 2, roomNumber: 'B/405', floorNumber: 4 },
  { buildingId: 2, roomNumber: 'B/406', floorNumber: 4 },
  { buildingId: 2, roomNumber: 'B/407', floorNumber: 4 },
  { buildingId: 2, roomNumber: 'B/408', floorNumber: 4 },

  { buildingId: 2, roomNumber: 'B/501', floorNumber: 5 },
  { buildingId: 2, roomNumber: 'B/502', floorNumber: 5 },
  { buildingId: 2, roomNumber: 'B/503', floorNumber: 5 },
  { buildingId: 2, roomNumber: 'B/504', floorNumber: 5 },
  { buildingId: 2, roomNumber: 'B/505', floorNumber: 5 },
  { buildingId: 2, roomNumber: 'B/506', floorNumber: 5 },
  { buildingId: 2, roomNumber: 'B/507', floorNumber: 5 },
  { buildingId: 2, roomNumber: 'B/508', floorNumber: 5 },

  { buildingId: 2, roomNumber: 'B/601', floorNumber: 6 },
  { buildingId: 2, roomNumber: 'B/602', floorNumber: 6 },
  { buildingId: 2, roomNumber: 'B/603', floorNumber: 6 },
  { buildingId: 2, roomNumber: 'B/604', floorNumber: 6 },
  { buildingId: 2, roomNumber: 'B/605', floorNumber: 6 },
  { buildingId: 2, roomNumber: 'B/606', floorNumber: 6 },
  { buildingId: 2, roomNumber: 'B/607', floorNumber: 6 },
  { buildingId: 2, roomNumber: 'B/608', floorNumber: 6 },

  { buildingId: 2, roomNumber: 'B/701', floorNumber: 7 },
  { buildingId: 2, roomNumber: 'B/702', floorNumber: 7 },
  { buildingId: 2, roomNumber: 'B/703', floorNumber: 7 },
  { buildingId: 2, roomNumber: 'B/704', floorNumber: 7 },
  { buildingId: 2, roomNumber: 'B/705', floorNumber: 7 },
  { buildingId: 2, roomNumber: 'B/706', floorNumber: 7 },
  { buildingId: 2, roomNumber: 'B/707', floorNumber: 7 },
  { buildingId: 2, roomNumber: 'B/708', floorNumber: 7 },

  { buildingId: 2, roomNumber: 'B/801', floorNumber: 8 },
  { buildingId: 2, roomNumber: 'B/802', floorNumber: 8 },
  { buildingId: 2, roomNumber: 'B/803', floorNumber: 8 },
  { buildingId: 2, roomNumber: 'B/804', floorNumber: 8 },
  { buildingId: 2, roomNumber: 'B/805', floorNumber: 8 },
  { buildingId: 2, roomNumber: 'B/806', floorNumber: 8 },
  { buildingId: 2, roomNumber: 'B/807', floorNumber: 8 },
  { buildingId: 2, roomNumber: 'B/808', floorNumber: 8 },

  { buildingId: 2, roomNumber: 'B/901', floorNumber: 9 },
  { buildingId: 2, roomNumber: 'B/902', floorNumber: 9 },
  { buildingId: 2, roomNumber: 'B/903', floorNumber: 9 },
  { buildingId: 2, roomNumber: 'B/904', floorNumber: 9 },
  { buildingId: 2, roomNumber: 'B/905', floorNumber: 9 },
  { buildingId: 2, roomNumber: 'B/906', floorNumber: 9 },
  { buildingId: 2, roomNumber: 'B/907', floorNumber: 9 },
  { buildingId: 2, roomNumber: 'B/908', floorNumber: 9 },

  { buildingId: 2, roomNumber: 'B/1001', floorNumber: 10 },
  { buildingId: 2, roomNumber: 'B/1002', floorNumber: 10 },
  { buildingId: 2, roomNumber: 'B/1003', floorNumber: 10 },
  { buildingId: 2, roomNumber: 'B/1004', floorNumber: 10 },
  { buildingId: 2, roomNumber: 'B/1005', floorNumber: 10 },
  { buildingId: 2, roomNumber: 'B/1006', floorNumber: 10 },
  { buildingId: 2, roomNumber: 'B/1007', floorNumber: 10 },
  { buildingId: 2, roomNumber: 'B/1008', floorNumber: 10 },

  { buildingId: 2, roomNumber: 'B/1101', floorNumber: 11 },
  { buildingId: 2, roomNumber: 'B/1102', floorNumber: 11 },
  { buildingId: 2, roomNumber: 'B/1103', floorNumber: 11 },
  { buildingId: 2, roomNumber: 'B/1104', floorNumber: 11 },
  { buildingId: 2, roomNumber: 'B/1105', floorNumber: 11 },
  { buildingId: 2, roomNumber: 'B/1106', floorNumber: 11 },
  { buildingId: 2, roomNumber: 'B/1107', floorNumber: 11 },
  { buildingId: 2, roomNumber: 'B/1108', floorNumber: 11 },

  { buildingId: 2, roomNumber: 'B/1201', floorNumber: 12 },
  { buildingId: 2, roomNumber: 'B/1202', floorNumber: 12 },
  { buildingId: 2, roomNumber: 'B/1203', floorNumber: 12 },
  { buildingId: 2, roomNumber: 'B/1204', floorNumber: 12 },
  { buildingId: 2, roomNumber: 'B/1205', floorNumber: 12 },
  { buildingId: 2, roomNumber: 'B/1206', floorNumber: 12 },
  { buildingId: 2, roomNumber: 'B/1207', floorNumber: 12 },
  { buildingId: 2, roomNumber: 'B/1208', floorNumber: 12 },

  { buildingId: 2, roomNumber: 'B/1301', floorNumber: 13 },
  { buildingId: 2, roomNumber: 'B/1302', floorNumber: 13 },
  { buildingId: 2, roomNumber: 'B/1303', floorNumber: 13 },
  { buildingId: 2, roomNumber: 'B/1304', floorNumber: 13 },
  { buildingId: 2, roomNumber: 'B/1305', floorNumber: 13 },
  { buildingId: 2, roomNumber: 'B/1306', floorNumber: 13 },
  { buildingId: 2, roomNumber: 'B/1307', floorNumber: 13 },
  { buildingId: 2, roomNumber: 'B/1308', floorNumber: 13 },

  { buildingId: 2, roomNumber: 'B/1401', floorNumber: 14 },
  { buildingId: 2, roomNumber: 'B/1402', floorNumber: 14 },
  { buildingId: 2, roomNumber: 'B/1403', floorNumber: 14 },
  { buildingId: 2, roomNumber: 'B/1404', floorNumber: 14 },
  { buildingId: 2, roomNumber: 'B/1405', floorNumber: 14 },
  { buildingId: 2, roomNumber: 'B/1406', floorNumber: 14 },
  { buildingId: 2, roomNumber: 'B/1407', floorNumber: 14 },
  { buildingId: 2, roomNumber: 'B/1408', floorNumber: 14 },

  { buildingId: 2, roomNumber: 'B/1501', floorNumber: 15 },
  { buildingId: 2, roomNumber: 'B/1502', floorNumber: 15 },
  { buildingId: 2, roomNumber: 'B/1503', floorNumber: 15 },
  { buildingId: 2, roomNumber: 'B/1504', floorNumber: 15 },
  { buildingId: 2, roomNumber: 'B/1505', floorNumber: 15 },
  { buildingId: 2, roomNumber: 'B/1506', floorNumber: 15 },
  { buildingId: 2, roomNumber: 'B/1507', floorNumber: 15 },
  { buildingId: 2, roomNumber: 'B/1508', floorNumber: 15 },

  { buildingId: 3, roomNumber: 'C/101', floorNumber: 1 },
  { buildingId: 3, roomNumber: 'C/102', floorNumber: 1 },
  { buildingId: 3, roomNumber: 'C/103', floorNumber: 1 },
  { buildingId: 3, roomNumber: 'C/104', floorNumber: 1 },
  { buildingId: 3, roomNumber: 'C/105', floorNumber: 1 },
  { buildingId: 3, roomNumber: 'C/106', floorNumber: 1 },
  { buildingId: 3, roomNumber: 'C/107', floorNumber: 1 },
  { buildingId: 3, roomNumber: 'C/108', floorNumber: 1 },

  { buildingId: 3, roomNumber: 'C/201', floorNumber: 2 },
  { buildingId: 3, roomNumber: 'C/202', floorNumber: 2 },
  { buildingId: 3, roomNumber: 'C/203', floorNumber: 2 },
  { buildingId: 3, roomNumber: 'C/204', floorNumber: 2 },
  { buildingId: 3, roomNumber: 'C/205', floorNumber: 2 },
  { buildingId: 3, roomNumber: 'C/206', floorNumber: 2 },
  { buildingId: 3, roomNumber: 'C/207', floorNumber: 2 },
  { buildingId: 3, roomNumber: 'C/208', floorNumber: 2 },

  { buildingId: 3, roomNumber: 'C/301', floorNumber: 3 },
  { buildingId: 3, roomNumber: 'C/302', floorNumber: 3 },
  { buildingId: 3, roomNumber: 'C/303', floorNumber: 3 },
  { buildingId: 3, roomNumber: 'C/304', floorNumber: 3 },
  { buildingId: 3, roomNumber: 'C/305', floorNumber: 3 },
  { buildingId: 3, roomNumber: 'C/306', floorNumber: 3 },
  { buildingId: 3, roomNumber: 'C/307', floorNumber: 3 },
  { buildingId: 3, roomNumber: 'C/308', floorNumber: 3 },

  { buildingId: 3, roomNumber: 'C/401', floorNumber: 4 },
  { buildingId: 3, roomNumber: 'C/402', floorNumber: 4 },
  { buildingId: 3, roomNumber: 'C/403', floorNumber: 4 },
  { buildingId: 3, roomNumber: 'C/404', floorNumber: 4 },
  { buildingId: 3, roomNumber: 'C/405', floorNumber: 4 },
  { buildingId: 3, roomNumber: 'C/406', floorNumber: 4 },
  { buildingId: 3, roomNumber: 'C/407', floorNumber: 4 },
  { buildingId: 3, roomNumber: 'C/408', floorNumber: 4 },

  { buildingId: 3, roomNumber: 'C/501', floorNumber: 5 },
  { buildingId: 3, roomNumber: 'C/502', floorNumber: 5 },
  { buildingId: 3, roomNumber: 'C/503', floorNumber: 5 },
  { buildingId: 3, roomNumber: 'C/504', floorNumber: 5 },
  { buildingId: 3, roomNumber: 'C/505', floorNumber: 5 },
  { buildingId: 3, roomNumber: 'C/506', floorNumber: 5 },
  { buildingId: 3, roomNumber: 'C/507', floorNumber: 5 },
  { buildingId: 3, roomNumber: 'C/508', floorNumber: 5 },

  { buildingId: 3, roomNumber: 'C/601', floorNumber: 6 },
  { buildingId: 3, roomNumber: 'C/602', floorNumber: 6 },
  { buildingId: 3, roomNumber: 'C/603', floorNumber: 6 },
  { buildingId: 3, roomNumber: 'C/604', floorNumber: 6 },
  { buildingId: 3, roomNumber: 'C/605', floorNumber: 6 },
  { buildingId: 3, roomNumber: 'C/606', floorNumber: 6 },
  { buildingId: 3, roomNumber: 'C/607', floorNumber: 6 },
  { buildingId: 3, roomNumber: 'C/608', floorNumber: 6 },

  { buildingId: 3, roomNumber: 'C/701', floorNumber: 7 },
  { buildingId: 3, roomNumber: 'C/702', floorNumber: 7 },
  { buildingId: 3, roomNumber: 'C/703', floorNumber: 7 },
  { buildingId: 3, roomNumber: 'C/704', floorNumber: 7 },
  { buildingId: 3, roomNumber: 'C/705', floorNumber: 7 },
  { buildingId: 3, roomNumber: 'C/706', floorNumber: 7 },
  { buildingId: 3, roomNumber: 'C/707', floorNumber: 7 },
  { buildingId: 3, roomNumber: 'C/708', floorNumber: 7 },

  { buildingId: 3, roomNumber: 'C/801', floorNumber: 8 },
  { buildingId: 3, roomNumber: 'C/802', floorNumber: 8 },
  { buildingId: 3, roomNumber: 'C/803', floorNumber: 8 },
  { buildingId: 3, roomNumber: 'C/804', floorNumber: 8 },
  { buildingId: 3, roomNumber: 'C/805', floorNumber: 8 },
  { buildingId: 3, roomNumber: 'C/806', floorNumber: 8 },
  { buildingId: 3, roomNumber: 'C/807', floorNumber: 8 },
  { buildingId: 3, roomNumber: 'C/808', floorNumber: 8 },

  { buildingId: 3, roomNumber: 'C/901', floorNumber: 9 },
  { buildingId: 3, roomNumber: 'C/902', floorNumber: 9 },
  { buildingId: 3, roomNumber: 'C/903', floorNumber: 9 },
  { buildingId: 3, roomNumber: 'C/904', floorNumber: 9 },
  { buildingId: 3, roomNumber: 'C/905', floorNumber: 9 },
  { buildingId: 3, roomNumber: 'C/906', floorNumber: 9 },
  { buildingId: 3, roomNumber: 'C/907', floorNumber: 9 },
  { buildingId: 3, roomNumber: 'C/908', floorNumber: 9 },

  { buildingId: 3, roomNumber: 'C/1001', floorNumber: 10 },
  { buildingId: 3, roomNumber: 'C/1002', floorNumber: 10 },
  { buildingId: 3, roomNumber: 'C/1003', floorNumber: 10 },
  { buildingId: 3, roomNumber: 'C/1004', floorNumber: 10 },
  { buildingId: 3, roomNumber: 'C/1005', floorNumber: 10 },
  { buildingId: 3, roomNumber: 'C/1006', floorNumber: 10 },
  { buildingId: 3, roomNumber: 'C/1007', floorNumber: 10 },
  { buildingId: 3, roomNumber: 'C/1008', floorNumber: 10 },

  { buildingId: 3, roomNumber: 'C/1101', floorNumber: 11 },
  { buildingId: 3, roomNumber: 'C/1102', floorNumber: 11 },
  { buildingId: 3, roomNumber: 'C/1103', floorNumber: 11 },
  { buildingId: 3, roomNumber: 'C/1104', floorNumber: 11 },
  { buildingId: 3, roomNumber: 'C/1105', floorNumber: 11 },
  { buildingId: 3, roomNumber: 'C/1106', floorNumber: 11 },
  { buildingId: 3, roomNumber: 'C/1107', floorNumber: 11 },
  { buildingId: 3, roomNumber: 'C/1108', floorNumber: 11 },

  { buildingId: 3, roomNumber: 'C/1201', floorNumber: 12 },
  { buildingId: 3, roomNumber: 'C/1202', floorNumber: 12 },
  { buildingId: 3, roomNumber: 'C/1203', floorNumber: 12 },
  { buildingId: 3, roomNumber: 'C/1204', floorNumber: 12 },
  { buildingId: 3, roomNumber: 'C/1205', floorNumber: 12 },
  { buildingId: 3, roomNumber: 'C/1206', floorNumber: 12 },
  { buildingId: 3, roomNumber: 'C/1207', floorNumber: 12 },
  { buildingId: 3, roomNumber: 'C/1208', floorNumber: 12 },

  { buildingId: 3, roomNumber: 'C/1301', floorNumber: 13 },
  { buildingId: 3, roomNumber: 'C/1302', floorNumber: 13 },
  { buildingId: 3, roomNumber: 'C/1303', floorNumber: 13 },
  { buildingId: 3, roomNumber: 'C/1304', floorNumber: 13 },
  { buildingId: 3, roomNumber: 'C/1305', floorNumber: 13 },
  { buildingId: 3, roomNumber: 'C/1306', floorNumber: 13 },
  { buildingId: 3, roomNumber: 'C/1307', floorNumber: 13 },
  { buildingId: 3, roomNumber: 'C/1308', floorNumber: 13 },

  { buildingId: 3, roomNumber: 'C/1401', floorNumber: 14 },
  { buildingId: 3, roomNumber: 'C/1402', floorNumber: 14 },
  { buildingId: 3, roomNumber: 'C/1403', floorNumber: 14 },
  { buildingId: 3, roomNumber: 'C/1404', floorNumber: 14 },
  { buildingId: 3, roomNumber: 'C/1405', floorNumber: 14 },
  { buildingId: 3, roomNumber: 'C/1406', floorNumber: 14 },
  { buildingId: 3, roomNumber: 'C/1407', floorNumber: 14 },
  { buildingId: 3, roomNumber: 'C/1408', floorNumber: 14 },

  { buildingId: 3, roomNumber: 'C/1501', floorNumber: 15 },
  { buildingId: 3, roomNumber: 'C/1502', floorNumber: 15 },
  { buildingId: 3, roomNumber: 'C/1503', floorNumber: 15 },
  { buildingId: 3, roomNumber: 'C/1504', floorNumber: 15 },
  { buildingId: 3, roomNumber: 'C/1505', floorNumber: 15 },
  { buildingId: 3, roomNumber: 'C/1506', floorNumber: 15 },
  { buildingId: 3, roomNumber: 'C/1507', floorNumber: 15 },
  { buildingId: 3, roomNumber: 'C/1508', floorNumber: 15 },

  { buildingId: 4, roomNumber: 'D/101', floorNumber: 1 },
  { buildingId: 4, roomNumber: 'D/103', floorNumber: 1 },
  { buildingId: 4, roomNumber: 'D/104', floorNumber: 1 },
  { buildingId: 4, roomNumber: 'D/102', floorNumber: 1 },
  { buildingId: 4, roomNumber: 'D/105', floorNumber: 1 },
  { buildingId: 4, roomNumber: 'D/106', floorNumber: 1 },
  { buildingId: 4, roomNumber: 'D/107', floorNumber: 1 },
  { buildingId: 4, roomNumber: 'D/108', floorNumber: 1 },

  { buildingId: 4, roomNumber: 'D/201', floorNumber: 2 },
  { buildingId: 4, roomNumber: 'D/202', floorNumber: 2 },
  { buildingId: 4, roomNumber: 'D/203', floorNumber: 2 },
  { buildingId: 4, roomNumber: 'D/204', floorNumber: 2 },
  { buildingId: 4, roomNumber: 'D/205', floorNumber: 2 },
  { buildingId: 4, roomNumber: 'D/206', floorNumber: 2 },
  { buildingId: 4, roomNumber: 'D/207', floorNumber: 2 },
  { buildingId: 4, roomNumber: 'D/208', floorNumber: 2 },

  { buildingId: 4, roomNumber: 'D/301', floorNumber: 3 },
  { buildingId: 4, roomNumber: 'D/302', floorNumber: 3 },
  { buildingId: 4, roomNumber: 'D/303', floorNumber: 3 },
  { buildingId: 4, roomNumber: 'D/304', floorNumber: 3 },
  { buildingId: 4, roomNumber: 'D/305', floorNumber: 3 },
  { buildingId: 4, roomNumber: 'D/306', floorNumber: 3 },
  { buildingId: 4, roomNumber: 'D/307', floorNumber: 3 },
  { buildingId: 4, roomNumber: 'D/308', floorNumber: 3 },

  { buildingId: 4, roomNumber: 'D/401', floorNumber: 4 },
  { buildingId: 4, roomNumber: 'D/402', floorNumber: 4 },
  { buildingId: 4, roomNumber: 'D/403', floorNumber: 4 },
  { buildingId: 4, roomNumber: 'D/404', floorNumber: 4 },
  { buildingId: 4, roomNumber: 'D/405', floorNumber: 4 },
  { buildingId: 4, roomNumber: 'D/406', floorNumber: 4 },
  { buildingId: 4, roomNumber: 'D/407', floorNumber: 4 },
  { buildingId: 4, roomNumber: 'D/408', floorNumber: 4 },

  { buildingId: 4, roomNumber: 'D/501', floorNumber: 5 },
  { buildingId: 4, roomNumber: 'D/502', floorNumber: 5 },
  { buildingId: 4, roomNumber: 'D/503', floorNumber: 5 },
  { buildingId: 4, roomNumber: 'D/504', floorNumber: 5 },
  { buildingId: 4, roomNumber: 'D/505', floorNumber: 5 },
  { buildingId: 4, roomNumber: 'D/506', floorNumber: 5 },
  { buildingId: 4, roomNumber: 'D/507', floorNumber: 5 },
  { buildingId: 4, roomNumber: 'D/508', floorNumber: 5 },

  { buildingId: 4, roomNumber: 'D/601', floorNumber: 6 },
  { buildingId: 4, roomNumber: 'D/602', floorNumber: 6 },
  { buildingId: 4, roomNumber: 'D/603', floorNumber: 6 },
  { buildingId: 4, roomNumber: 'D/604', floorNumber: 6 },
  { buildingId: 4, roomNumber: 'D/605', floorNumber: 6 },
  { buildingId: 4, roomNumber: 'D/606', floorNumber: 6 },
  { buildingId: 4, roomNumber: 'D/607', floorNumber: 6 },
  { buildingId: 4, roomNumber: 'D/608', floorNumber: 6 },

  { buildingId: 4, roomNumber: 'D/701', floorNumber: 7 },
  { buildingId: 4, roomNumber: 'D/702', floorNumber: 7 },
  { buildingId: 4, roomNumber: 'D/703', floorNumber: 7 },
  { buildingId: 4, roomNumber: 'D/704', floorNumber: 7 },
  { buildingId: 4, roomNumber: 'D/705', floorNumber: 7 },
  { buildingId: 4, roomNumber: 'D/706', floorNumber: 7 },
  { buildingId: 4, roomNumber: 'D/707', floorNumber: 7 },
  { buildingId: 4, roomNumber: 'D/708', floorNumber: 7 },

  { buildingId: 4, roomNumber: 'D/801', floorNumber: 8 },
  { buildingId: 4, roomNumber: 'D/802', floorNumber: 8 },
  { buildingId: 4, roomNumber: 'D/803', floorNumber: 8 },
  { buildingId: 4, roomNumber: 'D/804', floorNumber: 8 },
  { buildingId: 4, roomNumber: 'D/805', floorNumber: 8 },
  { buildingId: 4, roomNumber: 'D/806', floorNumber: 8 },
  { buildingId: 4, roomNumber: 'D/807', floorNumber: 8 },
  { buildingId: 4, roomNumber: 'D/808', floorNumber: 8 },

  { buildingId: 4, roomNumber: 'D/901', floorNumber: 9 },
  { buildingId: 4, roomNumber: 'D/902', floorNumber: 9 },
  { buildingId: 4, roomNumber: 'D/903', floorNumber: 9 },
  { buildingId: 4, roomNumber: 'D/904', floorNumber: 9 },
  { buildingId: 4, roomNumber: 'D/905', floorNumber: 9 },
  { buildingId: 4, roomNumber: 'D/906', floorNumber: 9 },
  { buildingId: 4, roomNumber: 'D/907', floorNumber: 9 },
  { buildingId: 4, roomNumber: 'D/908', floorNumber: 9 },

  { buildingId: 4, roomNumber: 'D/1001', floorNumber: 10 },
  { buildingId: 4, roomNumber: 'D/1002', floorNumber: 10 },
  { buildingId: 4, roomNumber: 'D/1003', floorNumber: 10 },
  { buildingId: 4, roomNumber: 'D/1004', floorNumber: 10 },
  { buildingId: 4, roomNumber: 'D/1005', floorNumber: 10 },
  { buildingId: 4, roomNumber: 'D/1006', floorNumber: 10 },
  { buildingId: 4, roomNumber: 'D/1007', floorNumber: 10 },
  { buildingId: 4, roomNumber: 'D/1008', floorNumber: 10 },

  { buildingId: 4, roomNumber: 'D/1101', floorNumber: 11 },
  { buildingId: 4, roomNumber: 'D/1102', floorNumber: 11 },
  { buildingId: 4, roomNumber: 'D/1103', floorNumber: 11 },
  { buildingId: 4, roomNumber: 'D/1104', floorNumber: 11 },
  { buildingId: 4, roomNumber: 'D/1105', floorNumber: 11 },
  { buildingId: 4, roomNumber: 'D/1106', floorNumber: 11 },
  { buildingId: 4, roomNumber: 'D/1107', floorNumber: 11 },
  { buildingId: 4, roomNumber: 'D/1108', floorNumber: 11 },

  { buildingId: 4, roomNumber: 'D/1201', floorNumber: 12 },
  { buildingId: 4, roomNumber: 'D/1202', floorNumber: 12 },
  { buildingId: 4, roomNumber: 'D/1203', floorNumber: 12 },
  { buildingId: 4, roomNumber: 'D/1204', floorNumber: 12 },
  { buildingId: 4, roomNumber: 'D/1205', floorNumber: 12 },
  { buildingId: 4, roomNumber: 'D/1206', floorNumber: 12 },
  { buildingId: 4, roomNumber: 'D/1207', floorNumber: 12 },
  { buildingId: 4, roomNumber: 'D/1208', floorNumber: 12 },

  { buildingId: 4, roomNumber: 'D/1301', floorNumber: 13 },
  { buildingId: 4, roomNumber: 'D/1302', floorNumber: 13 },
  { buildingId: 4, roomNumber: 'D/1303', floorNumber: 13 },
  { buildingId: 4, roomNumber: 'D/1304', floorNumber: 13 },
  { buildingId: 4, roomNumber: 'D/1305', floorNumber: 13 },
  { buildingId: 4, roomNumber: 'D/1306', floorNumber: 13 },
  { buildingId: 4, roomNumber: 'D/1307', floorNumber: 13 },
  { buildingId: 4, roomNumber: 'D/1308', floorNumber: 13 },

  { buildingId: 4, roomNumber: 'D/1401', floorNumber: 14 },
  { buildingId: 4, roomNumber: 'D/1402', floorNumber: 14 },
  { buildingId: 4, roomNumber: 'D/1403', floorNumber: 14 },
  { buildingId: 4, roomNumber: 'D/1404', floorNumber: 14 },
  { buildingId: 4, roomNumber: 'D/1405', floorNumber: 14 },
  { buildingId: 4, roomNumber: 'D/1406', floorNumber: 14 },
  { buildingId: 4, roomNumber: 'D/1407', floorNumber: 14 },
  { buildingId: 4, roomNumber: 'D/1408', floorNumber: 14 },

  { buildingId: 4, roomNumber: 'D/1501', floorNumber: 15 },
  { buildingId: 4, roomNumber: 'D/1502', floorNumber: 15 },
  { buildingId: 4, roomNumber: 'D/1503', floorNumber: 15 },
  { buildingId: 4, roomNumber: 'D/1504', floorNumber: 15 },
  { buildingId: 4, roomNumber: 'D/1505', floorNumber: 15 },
  { buildingId: 4, roomNumber: 'D/1506', floorNumber: 15 },
  { buildingId: 4, roomNumber: 'D/1507', floorNumber: 15 },
  { buildingId: 4, roomNumber: 'D/1508', floorNumber: 15 }
];

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert({ schema: 'public', tableName: 'Floor' }, floorData, {});
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete({ schema: 'public', tableName: 'Floor' }, null, {});
  }
};